services:
  - type: web
    name: houses-price-prediction
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --access-logfile - --error-logfile - app:app
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///users.db
      - key: MODEL_PATH
        value: model.pkl
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: REMEMBER_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_HTTPONLY
        value: "true"
      - key: REMEMBER_COOKIE_HTTPONLY
        value: "true"
      - key: DEBUG
        value: "false"
      - key: TESTING
        value: "false"
      - key: PYTHONUNBUFFERED
        value: "1" 